### ISSUE TITLE
PEOPLE: Austritt mit Gründen und Datenschutz-Flag

### ISSUE THREAD

**Issue by tobiasstern** [hitobito/hitobito_sac_cas#141]
Follow up zu #133 

Bei Austritt sollen die User einen Grund für den Austritt angeben und ausserdem sollen sie die dauerhafte Aufbewahrung ihrer Daten auswählen können.

Beim Austritt aus einer Zusatzsektion soll dieser Dialog angezeigt werden:

![image](https://github.com/hitobito/hitobito_sac_cas/assets/11408951/ed8f0879-1387-4452-a8ec-8231cdb028e3)

Bei Austritt aus der Stammsektion und damit Austritt aus dem SAC:

![image](https://github.com/hitobito/hitobito_sac_cas/assets/11408951/b76c1129-82c4-4a6f-9229-342439a697d7)

Der Text aus dem Bild:

> Nach deinem Austritt bewahren wir deine Daten noch sechs Monate lang auf, bevor wir sie endgültig löschen. Die Löschung hat für dich die folgenden Konsequenzen:
> - Falls du später dem SAC wieder beitreten möchtest, musst du die Eintrittsgebühr erneut bezahlen und deine Anzahl Mitgliederjahre beginnen bei null. 
> - Sofern vorhanden werden erlangte Qualifikationen und absolvierte Aus- und Weiterbildungen (inklusive Fortbildungsstunden) gelöscht.
> - Dein SAC-Login wird gelöscht und du kannst es nicht mehr für andere Zwecke verwenden (z.b. die SAC App).
> 
> Falls du dies nicht möchtest, musst du uns hier erlauben, deine Daten länger als sechs Monate aufzubewahren:

# Tech-Spec

# ToDo

**Comment by sykesonrocks** [comment]
Hinsichtlich Mockups:
- Austritte sind immer nur per 31.12 möglich. Ein Sofortaustritt und ein Austritt per<>31.12 wird nicht zugelassen.
- "Begründung" sollte umbenannt werden zu "Austrittgrund". Das Feld soll optional sein.
- Die negativen Konsequenzen einer Datenlöschung in Bezug auf das SAC Login muss im Text klar beschrieben sein (siehe unten).

Hinsichtlich Datenlöschung/Datenschutz:
Aktuelle Hypothese ist, dass eine Datenlöschung 6 Monate nach Austritt eintritt, wenn beim ausgetretenen Mitglied nicht nachgewiesen werden kann, dass eine Zustimmung gegeben wurde, dass der SAC die Daten weiterhin aufbewahren darf (grundsätzlich gilt “Privacy by Design und Privacy by Default“). Die Zustimmung muss in Hitobito erfasst sein (z.B. eine E-Mail genügt nicht). 
Falls eine Datenlöschung eintritt, werden alle Personendaten des ausgetretenen Mitglieds in Hitobito gelöscht (mit Ausnahme der Mitgliedernummer zugunsten Mitgliederstatistik). Dies hat folgende Konsequenzen:
- Ein Wiedereintritt ist nicht mehr möglich. Hitobito erkennt keine Dublette.
- Sofern es sich beim Mitglied um einen Kursteilnehmer handelt, würden sämtliche Qualifikationen, Fortbildungsstunden inkl. Aus- und Weiterbildungshistory ebenfalls gelöscht werden (betrifft insbesondere Tourenleiter).
- Das Hitobito Konto wird gelöscht und damit hat das austretende Mitglied kein SAC Login mehr (z.B. für die SAC App, Tourenportal). Wenn weiterhin ein SAC Login benötigt wird, muss ein FAN-Konto nach dem Austritt eröffnet werden.
Fall keine Datenlöschung eintritt, werden keine Personendaten des ausgetretenen Mitglieds in Hitobito gelöscht. Das Hitobito Konto bleibt bestehen und damit das SAC Login. Lediglich die zugewiesenen Beitragskategorien resp. Rollen werden auf 31.12 terminiert. Dieser Zustand des Kontos ist mit einem FAN-Konto vergleichbar.

**Comment by tobiasstern** [comment]
Habe die Spez und die Mockups oben aktualisiert.

@sykesonrocks Haben wir die Texte für Austrittsgründe schon irgendwo? Und kannst du bitte den Infotext-Vorschlag zu Aufbewahrung verifizieren?

**Comment by sykesonrocks** [comment]
@tobiasstern Nimm es bitte mit Sandro auf, danke.

**Comment by tobiasstern** [comment]
Ist aufgenommen und im doing 👍

**Comment by mtnstar** [comment]
Spezifikation muss noch weiter ausgearbeitet werden:

- Wie werden die Personendaten anonymisiert falls Daten gelöscht werden?
- Was ist alles in diesem Ticket beinhaltet?
- Was genau passiert wenn jemand sich entscheidet das die Daten behalten werden können?
- ...
